# Generated by Django 6.0.5 on 2026-05-11 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMealSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('pantry_hash', models.CharField(max_length=64)),
                ('week_start', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_meal_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=60)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_time_minutes', models.IntegerField()),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('category', models.CharField(max_length=30)),
                ('match_score', models.FloatField(default=0.0)),
                ('matched_ingredients', models.JSONField(default=list)),
                ('missing_ingredients', models.JSONField(default=list)),
                ('substitutions', models.JSONField(default=dict)),
                ('meal_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meals.generatedmealset')),
            ],
            options={
                'ordering': ['-match_score', 'title'],
            },
        ),
    ]
